[package]
name = "pacrust"
version = "0.1.0"
authors = ["Lucas Godoy <lcsdegodoy@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
